version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.github.spotbugs
    versions:
    - 4.6.0
    - 4.6.1
    - 4.6.2
    - 4.7.0
  - dependency-name: com.google.guava:guava
    versions:
    - 30.1-jre
  - dependency-name: com.ibm.icu:icu4j
    versions:
    - "68.2"
  - dependency-name: org.apache.wicket:wicket-core
    versions:
    - 9.2.0
