version: 2

jobs:
  build:
    docker:
      - image: classmethod/openjdk-with-git:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - baseunits-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - baseunits-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}
            - baseunits-{{ .Branch }}
            - baseunits-develop
            - baseunits-master
      - run:
          name: Show gradle version
          command: ./gradlew -v
      - run:
          name: Download gradle dependencies
          command: ./gradlew dependencies
      - run:
          name: Run tests
          command: ./gradlew clean check
      - store_artifacts:
          name: Store artifacts
          path: build/reports
      - store_test_results:
          path: build/test-results
      - deploy:
          name: Deploy artifacts
          command: |
            ./gradlew publish showVersion
      - save_cache:
          key: baseunits-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - "~/.gradle"
            - "~/.m2"
